name: Feature request
description: Propose an enhancement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Related version/tag (optional)
      description: Relevant version target or tag.
